# Generated by Django 4.2.2 on 2025-04-17 01:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('date_membership', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
            ],
            options={
                'verbose_name': 'عضو خبرنامه',
                'verbose_name_plural': 'اعضای خبرنامه',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن درباره ما')),
                ('contact_us_text', models.TextField(verbose_name='متن تماس با ما')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='شماره تلفن')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='ایمیل')),
                ('copy_right', models.CharField(max_length=255, verbose_name='متن کپی رایت')),
                ('instagram_link', models.CharField(blank=True, default='https://instagram.com/username', max_length=250, null=True, verbose_name='لینک اینستاگرام')),
                ('telegram_link', models.CharField(blank=True, default='https://t.me/username', max_length=250, null=True, verbose_name='لینک تلگرام')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
